### ISSUE TITLE
Document values.yml

### ISSUE THREAD

**Issue by marcofranssen** [philips-labs/dctna-helm#3]
Using following syntax a helm chart can be documented.

https://github.com/norwoodj/helm-docs will pickup the values.

```yml
# web -- configuration for web component
web:
  # web.ingress -- configuration for web ingress
  ingress:
    # web.ingress.enabled -- enables or disables the ingress
    enabled: true
```
